# Chapter 3 Python Numpy 예제 요약

이 노트북은 `Example-03-24-Py`부터 `Example-03-35-Py`까지의 내용을 한 번에 정리한 실행형 요약입니다.

| 예제 | 핵심 내용 |
|---|---|
| 03-24 | 1D/2D/3D 배열 인덱싱 |
| 03-25 | 중첩 배열에서 짝수만 추출 |
| 03-26 | 슬라이싱으로 부분 배열 선택 |
| 03-27 | reshape / order='F' |
| 03-28 | np.newaxis로 차원 추가 |
| 03-29 | flatten / ravel 비교 |
| 03-30 | stack으로 배열 병합 |
| 03-31 | split으로 배열 분리 |
| 03-32 | 브로드캐스팅 덧셈 |
| 03-33 | 행렬 곱과 거듭제곱 |
| 03-34 | ROI(부분 배열) |
| 03-35 | 채널 분리 |

아래 코드 셀에서 각 예제의 핵심 출력 형태를 순서대로 확인할 수 있습니다.

## 실행 코드

아래 셀은 각 예제를 짧게 재현합니다. 원본 파일의 동작을 한 화면에서 확인하기 위한 정리용 코드입니다.

In [1]:
import numpy as np

print('03-24 인덱싱')
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array1[-1])
print(array2[0][1])
print(array3[0][1][1])

print('\n03-25 짝수 필터링')
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in array[0]:
    for j in i:
        if j % 2 == 0:
            print(j)

print('\n03-26 슬라이싱')
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])
print(array[1:3])
print(array[::2])
print(array[2:, 1::2])

print('\n03-27 reshape')
array = np.arange(12)
reshape1 = array.reshape(2, 3, 2)
reshape2 = np.reshape(array, (2, -1), order='F')
print(reshape1)
print(reshape2)

print('\n03-28 newaxis')
array = np.arange(4)
axis1 = array[np.newaxis]
axis2 = array[:, np.newaxis]
print(axis1)
print(axis2)

print('\n03-29 flatten / ravel')
array = np.arange(12).reshape(3, -1)
flat1 = array.flatten(order='F')
flat2 = array.ravel()
print(flat1)
print(flat2)

print('\n03-30 stack')
array1 = np.arange(6).reshape(2, 3)
array2 = np.arange(6, 12).reshape(2, 3)
merge1 = np.stack([array1, array2], axis=0)
merge2 = np.stack([array1, array2], axis=-1)
print(merge1)
print(merge2)

print('\n03-31 split')
array = np.arange(10).reshape(2, 5)
detach1 = np.split(array, 2, axis=0)
detach2 = np.split(array, [2, 3], axis=1)
print(detach1)
print(detach2)

print('\n03-32 broadcasting')
array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array2 = np.array([1.5, 2.5])
print(array1 + array2)

print('\n03-33 matrix')
array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array2 = np.array([5, 6, 7, 8]).reshape(2, 2)
mat1 = np.matrix(array1)
mat2 = np.matrix(array2)
print(mat1.T * mat2)
print(mat1 ** 2)

print('\n03-34 ROI')
array = np.zeros((1280, 1920, 3), np.uint8)
x, y, w, h = 100, 100, 300, 300
roi = array[x:x+w, y:y+h]
print(array.shape)
print(roi.shape)

print('\n03-35 channel split')
array = np.zeros((1280, 1920, 3), np.uint8)
coi = array[:, :, 0]
print(array.shape)
print(coi.shape)

03-24 인덱싱
3
2
4

03-25 짝수 필터링
2
4

03-26 슬라이싱
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[12 14]
 [17 19]]

03-27 reshape
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]

03-28 newaxis
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]

03-29 flatten / ravel
[ 0  4  8  1  5  9  2  6 10  3  7 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

03-30 stack
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]

03-31 split
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0, 1],
       [5, 6]]), array([[2],
       [7]]), array([[3, 4],
       [8, 9]])]

03-32 broadcasting
[[2.5 4.5]
 [4.5 6.5]]

03-33 matrix
[[26 30]
 [38 44]]
[[ 7 10]
 [15 22]]

03-34 ROI
(1280, 1920, 3)
(300, 300, 3)

03-35 channel split
(1280, 1920, 3)
(1280, 1920)
